### ISSUE TITLE
Running `bash` command gave error code 127

### ISSUE THREAD

**Issue by lemorage** [tynanbe/shellout#10]
My code as follows:
```gleam
pub fn main() {
  let result = shellout.command("bash", ["-i", "-c", "\"echo $HISTFILE\""], ".", [])
  io.println(string.inspect(result))
}
```

When running it, I got the following error:
```sh
Error(#(127, "bash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nbash: echo /Users/clannad/.bash_
history: No such file or directory\n"))
```

**Comment by tynanbe** [comment]
Those error messages are due to a limitation when running a shellout `command` with Gleam's Erlang target, in this case because you attempt to run `bash` interactively (`-i`).

You can see that the command was still run, although your command is malformed in this case due to the unneeded quotes, so one option would be for you to fix that and try running it within a second shell command from which you can redirect stderr to `/dev/null`, (e.g. something like `command("bash", "-c", "bash -ic 'echo $HISTFILE' 2>/dev/null")`).

Perhaps a better approach is as follows:

```gleam
  let result =
    shellout.command(
      "bash",
      [
        "-o", "history", "-c",
        "
          echo $HOME
          echo $HISTFILE
        ",
      ],
      ".",
      [],
    )
  io.println(string.inspect(result))
```
